name: SQLiteDAV
version: '0.1.0.0'
homepage: https://github.com/Airsequel/SQLiteDAV#readme
github: Airsequel/SQLiteDAV
license: MIT
author: Adrian Sieber
category: Web, Database
extra-source-files:
  - README.md

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - directory
  - filepath
  - http-types
  - protolude
  - servant-foreign
  - servant-options
  - servant-server
  - sqlite-simple
  - text
  - time
  - unix
  - wai-extra
  - xml

default-extensions:
  - NoImplicitPrelude
  - OverloadedRecordDot
  - OverloadedStrings

library:
  source-dirs: src
  exposed-modules:
    - SQLiteDAV.API
    - SQLiteDAV.HTTPExtensions
    - SQLiteDAV.Properties
    - SQLiteDAV.Server
  language: GHC2021

executables:
  sqlitedav:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - optparse-generic
      - SQLiteDAV
      - wai-extra
      - warp
    language: GHC2021

tests:
  sqlitedav-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
    dependencies:
      - hspec
      - hspec-wai
      - SQLiteDAV
      - wai
    language: GHC2021
